revert previous bad commit partially

diff --git a/pkg_summary-utils/files/pkg_digger_backend.in b/pkg_summary-utils/files/pkg_digger_backend.in
--- a/pkg_summary-utils/files/pkg_digger_backend.in
+++ b/pkg_summary-utils/files/pkg_digger_backend.in
@@ -155,6 +155,14 @@ else
 
     cnt=1
     for i in "$@"; do
+#	if printf '%s\n' "$i" | grep ':.*:' > /dev/null; then
+#	    :
+#	else
+#	    echo "Invalid search pattern: '$i'," 1>&2
+#	    echo "   field:strategy:query is expected" 1>&2
+#	    exit 34
+#	fi
+
 	field=`echo "$i" | cut -d: -f1`
 	strat=`echo "$i" | cut -d: -f2`
 	query=`echo "$i" | cut -d: -f3`
@@ -189,6 +197,6 @@ else
 		print "No matches found" > "/dev/stderr"
 	    exit 20
 	}
-    }' "$tmp_dir"
+    }' "$tmp_dir"/*
     exit 0
 fi
