Check that pattern is in f:s:q format and warn otherwise

diff --git a/pkg_summary-utils/files/pkg_digger_backend.in b/pkg_summary-utils/files/pkg_digger_backend.in
--- a/pkg_summary-utils/files/pkg_digger_backend.in
+++ b/pkg_summary-utils/files/pkg_digger_backend.in
@@ -155,13 +155,13 @@ else
 
     cnt=1
     for i in "$@"; do
-#	if printf '%s\n' "$i" | grep ':.*:' > /dev/null; then
-#	    :
-#	else
-#	    echo "Invalid search pattern: '$i'," 1>&2
-#	    echo "   field:strategy:query is expected" 1>&2
-#	    exit 34
-#	fi
+	if printf '%s\n' "$i" | grep ':.*:' > /dev/null; then
+	    :
+	else
+	    echo "Invalid search pattern: '$i'," 1>&2
+	    echo "   field:strategy:query is expected" 1>&2
+	    exit 34
+	fi
 
 	field=`echo "$i" | cut -d: -f1`
 	strat=`echo "$i" | cut -d: -f2`
