pkg_digger: better handling of -1, -3 and -9 options

diff --git a/pkg_summary-utils/files/pkg_digger_backend.in b/pkg_summary-utils/files/pkg_digger_backend.in
--- a/pkg_summary-utils/files/pkg_digger_backend.in
+++ b/pkg_summary-utils/files/pkg_digger_backend.in
@@ -86,9 +86,9 @@ while getopts hsf139irqn: f; do
     case "$f" in
 	s)    pkg_grep_summary -T -T; exit 0;;
 	f)    show_fields;;
-	9|i)  info=1;;
-	3)    shortinfo=1; FIELDS=-f`echo $FIELDS_3 | tr ' ' ,`;;
-	1)    onelineinfo=1;;
+	9|i)  stype=9; unset FIELDS || true;;
+	3)    stype=3; FIELDS=-f`echo $FIELDS_3 | tr ' ' ,`;;
+	1)    stype=1; unset FIELDS || true;;
 	r)    raw_format=1;;
 	q)    quiet_mode=1;;
 	n)    limit=$OPTARG;;
@@ -129,74 +129,75 @@ summary2onelineinfo (){
 	}' "$@"
 }
 
-if test -n "$onelineinfo"; then
-    # -1
-    pkg_grep_summary -r -fPKGNAME,PKGPATH,COMMENT -i \
+case "$stype" in
+    1)
+	# -1
+	pkg_grep_summary -r -fPKGNAME,PKGPATH,COMMENT -i \
 	    -t strlist PKGPAIR "$*" < "$PKG_DIGGER_SUMMARY" |
-    summary2onelineinfo
+	summary2onelineinfo
 
-    exit 0
-elif test -n "${shortinfo}${info}"; then
-    # -3|-9
-    runpipe \
-	pkg_grep_summary $FIELDS -r -i \
+	exit 0;;
+    3|9)
+	# -3|-9
+	runpipe \
+	    pkg_grep_summary $FIELDS -r -i \
 	    -t strlist PKGPAIR "$*" < "$PKG_DIGGER_SUMMARY" '|' \
-	gen_summary4view
-    if test "$pipestatus_1" != 0; then
-	test "$quiet_mode" = 1 || echo 'No matches found' 1>&2
-	exit 20
-    fi
-
-    exit 0
-else
-    # f:s:q
-    tmp_dir=`mktemp -d /tmp/pkg_digger.XXXXXX`
-    trap "rm -rf $tmp_dir $new_summary" 0 1 2 15
-
-    cnt=1
-    for i in "$@"; do
-	if printf '%s\n' "$i" | grep ':.*:' > /dev/null; then
-	    :
-	else
-	    echo "Invalid search pattern: '$i'," 1>&2
-	    echo "   field:strategy:query is expected" 1>&2
-	    exit 34
+	    gen_summary4view
+	if test "$pipestatus_1" != 0; then
+	    test "$quiet_mode" = 1 || echo 'No matches found' 1>&2
+	    exit 20
 	fi
 
-	field=`echo "$i" | cut -d: -f1`
-	strat=`echo "$i" | cut -d: -f2`
-	query=`echo "$i" | cut -d: -f3`
-	pkg_grep_summary -fPKGNAME,PKGPATH,ASSIGNMENTS -i \
-	    -t "$strat" "$field" "$query" < "$PKG_DIGGER_SUMMARY" > "$tmp_dir/$cnt" &
-	cnt=$(($cnt+1))
-    done
-    wait 
-    runawk -v quiet_mode="$quiet_mode" -v limit="$limit" \
-	-e '
-    /^PKGPATH=/ {
-	pkgpath = substr($0, 9)
-	sub(/:.*/, "", pkgpath)
-	next
-    }
-    /^PKGNAME=/ {
-	pkgbase = substr($0, 9)
-	sub(/-[^-]*$/, "", pkgbase)
-	next
-    }
-    NF == 0 {
-	pkgpair = pkgpath "," pkgbase
-	if (pkgpair in hash)
+	exit 0;;
+    *)
+	# f:s:q
+	tmp_dir=`mktemp -d /tmp/pkg_digger.XXXXXX`
+	trap "rm -rf $tmp_dir $new_summary" 0 1 2 15
+
+	cnt=1
+	for i in "$@"; do
+	    if printf '%s\n' "$i" | grep ':.*:' > /dev/null; then
+		:
+	    else
+		echo "Invalid search pattern: '$i'," 1>&2
+		echo "   field:strategy:query is expected" 1>&2
+		exit 34
+	    fi
+
+	    field=`echo "$i" | cut -d: -f1`
+	    strat=`echo "$i" | cut -d: -f2`
+	    query=`echo "$i" | cut -d: -f3`
+	    pkg_grep_summary -fPKGNAME,PKGPATH,ASSIGNMENTS -i \
+		-t "$strat" "$field" "$query" < "$PKG_DIGGER_SUMMARY" > "$tmp_dir/$cnt" &
+	    cnt=$(($cnt+1))
+	done
+	wait 
+	runawk -v quiet_mode="$quiet_mode" -v limit="$limit" \
+	    -e '
+	/^PKGPATH=/ {
+	    pkgpath = substr($0, 9)
+	    sub(/:.*/, "", pkgpath)
 	    next
-	hash [pkgpair] = 1
-	print pkgpair
-	found = 1
-    }
-    END {
-	if (!found){
-	    if (!quiet_mode)
-		print "No matches found" > "/dev/stderr"
-	    exit 20
 	}
-    }' "$tmp_dir"/*
-    exit 0
-fi
+	/^PKGNAME=/ {
+	    pkgbase = substr($0, 9)
+	    sub(/-[^-]*$/, "", pkgbase)
+	    next
+	}
+	NF == 0 {
+	    pkgpair = pkgpath "," pkgbase
+	    if (pkgpair in hash)
+		next
+	    hash [pkgpair] = 1
+	    print pkgpair
+	    found = 1
+	}
+	END {
+	    if (!found){
+		if (!quiet_mode)
+		    print "No matches found" > "/dev/stderr"
+		exit 20
+	    }
+	}' "$tmp_dir"/*
+	exit 0;;
+esac
