Reworked the packaging of the AMD/ATI proprietary drivers to specify both stable and unstable releases.  The unstable driver can now coexist with the stable driver, and will not be picked up by default.
ati-xfree86-bin: Reverted from 8.40.4 to 8.38.6: 8.40.4 is unstable
    and can cause machine lockups and shouldn't be the default.

ati-xfree86-bin-init: removed, and merged initati functionality into
    ati-xfree86-bin-unstable

ati-xfree86-bin-unstable: This packages the 8.40.4 driver.  This package
    provides initiati, which uses the stable driver to initialize the card
    and thus depends on ati-xfree86-bin.

diff --git a/ati-xfree86-bin-unstable/files/initati b/ati-xfree86-bin-unstable/files/initati
--- a/ati-xfree86-bin-unstable/files/initati
+++ b/ati-xfree86-bin-unstable/files/initati
@@ -1,16 +1,22 @@
 #!/bin/sh
-# Run XFree86 with an older version of the proprietary AMD/ATI Linux
-# drivers so as to properly initialize some ATI card variants.
+# Run XFree86 with the stable version of the proprietary AMD/ATI Linux
+# drivers; necessary to properly initialize some ATI card variants.
 #
 # Unfortunately -probeonly doesn't seem to be sufficient, so we
 # need to actually start the server, and then send SIGTERM to cause
-# it to quit.
+# the server to quit.
 
 # We could just use the existing XF86Config and explicitly specify
-#    -modulepaths "@INITATIDIR@/,..."
+#    -modulepaths "@SHAREDIR@/,..."
 # but figuring out the other paths seems difficult.  And this way
 # we control what other extensions are loaded.
-XFree86 -xf86config @INITATIDIR@/XF86Config.initati \
+XF86CONFIG="@SHAREDIR@/XF86Config.initati"
+
+if [ ! -f "${XF86CONFIG}" ]; then
+    echo "error: ${XF86CONFIG} does not exist" 1>&2
+    exit 1
+fi
+XFree86 -xf86config "${XF86CONFIG}" \
     -nolisten tcp -nolisten inet6 \
     "$@" &
 
