- Update to GHC 6.10.1 - Use GHC 6.6.1 for bootstrapping compiler. - GHC now depends on editline instead of readline.

diff --git a/ghc/patches/patch-ab b/ghc/patches/patch-ab
--- a/ghc/patches/patch-ab
+++ b/ghc/patches/patch-ab
@@ -1,13 +1,29 @@
-$NetBSD: patch-ab,v 1.3 2008/07/17 14:45:25 phonohawk Exp $
+$NetBSD: patch-ab,v 1.4 2009/01/11 09:28:43 phonohawk Exp $
 
---- ../ghc-6.4.2/mk/bootstrap.mk.orig	2006-07-29 01:11:13.000000000 +0200
-+++ ../ghc-6.4.2/mk/bootstrap.mk	2006-07-29 01:12:31.000000000 +0200
-@@ -149,7 +149,7 @@
- HC_BOOT_LIBS += -lHSreadline -lHStemplate-haskell -lHSunix -lHSunix_cbits
- endif
+--- ../ghc-6.6.1/configure.orig	2007-04-26 02:29:16.000000000 +0900
++++ ../ghc-6.6.1/configure
+@@ -2590,20 +2590,12 @@ fi
+       exit 1
+    else
+    $PerlCmd -v >conftest.out 2>&1
+-   if grep "v5.6" conftest.out >/dev/null 2>&1; then
++   if grep "v5." conftest.out >/dev/null 2>&1; then
+       :
+    else
+-      if grep "v5.8" conftest.out >/dev/null 2>&1; then
+-         :
+-      else
+-         if grep "version 6" conftest.out >/dev/null 2>&1; then
+-            :
+-         else
+-            { { echo "$as_me:$LINENO: error: your version of perl probably won't work, try upgrading it." >&5
+-echo "$as_me: error: your version of perl probably won't work, try upgrading it." >&2;}
+-   { (exit 1); exit 1; }; }
+-         fi
+-      fi
++      { { echo "$as_me:$LINENO: error: your version of perl probably won't work, try upgrading it." >&5
++          echo "$as_me: error: your version of perl probably won't work, try upgrading it." >&2; }
++        { (exit 1); exit 1; }; }
+    fi
+ rm -fr conftest*
  
--HC_BOOT_LIBS +=  -lHSCabal -lHShaskell98 -lHSbase -lHSbase_cbits -lHSparsec -lHSrts -lgmp -lm $(EXTRA_HC_BOOT_LIBS)
-+HC_BOOT_LIBS +=  -lHSCabal -lHShaskell98 -lHSbase -lHSbase_cbits -lHSparsec -lHSrts -lgmp -Wl,-R@PREFIX@/lib -L@PREFIX@/lib -lm $(EXTRA_HC_BOOT_LIBS)
- 
- ifeq "$(GhcLibsWithReadline)" "YES"
- HC_BOOT_LIBS += $(patsubst %, -l%, $(LibsReadline))
