Updated audit-system(8) Added audit-system.conf(5) Install all man pages Add a check for all the tools we need in audit-system(8)

diff --git a/audit-system/files/audit-system b/audit-system/files/audit-system
--- a/audit-system/files/audit-system
+++ b/audit-system/files/audit-system
@@ -1,6 +1,6 @@
 #! @SH@
 #
-# $NetBSD: audit-system,v 1.2 2008/07/04 20:11:44 adrian_p Exp $
+# $NetBSD: audit-system,v 1.3 2008/07/05 19:07:21 adrian_p Exp $
 #
 # Copyright (c) 2008 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -65,6 +65,36 @@ download=no
 download_only=no
 verbose=no
 neednew=no
+tools="@STAT@ @OBJDUMP@ @CKSUM@ @FETCH_TOOL@ @IDENT@"
+
+# check the integrity of a system-vulnerabilities file
+check_integrity() 
+{
+	# see if the file got damaged while it was being downloaded
+	recordedsum=$(${AWK} '$1 == "#CHECKSUM" { print $3 }' $1)
+	recordedalg=$(${AWK} '$1 == "#CHECKSUM" { print $2 }' $1)
+
+	if [ "x${recordedsum}" = "x" -o "x${recordedalg}" = "x" ]; then
+		echo "ERROR: Error in downloading"
+		${RM} -f "$1"
+		exit 1
+	fi
+	
+	calcsum=$(${AWK} '$1 == "#CHECKSUM" || /\$NetBSD.*/ { next } { print }' $1 | ${CKSUM} ${recordedalg})
+	if [ "x${recordedsum}" != "x${calcsum}" ]; then
+		echo "ERROR: Checksum mismatch"
+		${RM} -f "$1"
+		exit 1
+	fi
+}
+
+# check all the tools we need are available
+for t in ${tools} ; do
+	if [ ! -x ${t} ]; then
+		echo "ERROR: Required tools not found"
+		exit 1
+	fi
+done
 
 # process any command line arguments
 while [ $# -gt 0 ]; do
@@ -133,22 +163,7 @@ if [ "x${download}" = "xyes" -o "x${download_only}" = "xyes" ]; then
 		exit 1
 	fi
 
-	# see if the file got damaged while it was being downloaded
-	recordedsum=$(${AWK} '$1 == "#CHECKSUM" { print $3 }' ${newvullist})
-	recordedalg=$(${AWK} '$1 == "#CHECKSUM" { print $2 }' ${newvullist})
-
-	if [ "x${recordedsum}" = "x" -o "x${recordedalg}" = "x" ]; then
-		echo "ERROR: Error in downloading"
-		${RM} -f "${newvullist}"
-		exit 1
-	fi
-	
-	calcsum=$(${AWK} '$1 == "#CHECKSUM" || /\$NetBSD.*/ { next } { print }' ${newvullist} | ${CKSUM} ${recordedalg})
-	if [ "x${recordedsum}" != "x${calcsum}" ]; then
-		echo "ERROR: Checksum mismatch"
-		${RM} -f "${newvullist}"
-		exit 1
-	fi
+	check_integrity "${newvullist}"
 
 	# test to see if file has been changed
 	if [ -f "${vuls}" ]; then
@@ -198,24 +213,24 @@ if [ -z "${file_teeny}" ] ; then
 	file_teeny=0
 fi
 
-if [ "x$file_major" = "x" -o "x$file_minor" = "x" ]; then
+if [ "x${file_major}" = "x" -o "x${file_minor}" = "x" ]; then
 	echo "ERROR: Error in downloading"
 	exit 1
 fi
 
-if [ "${file_major}" -ne "${FORMAT_MAJOR}" -o "${file_minor}" -gt "${FORMAT_MINOR}" ]; then
-	errmsg="Unsupported file format version"
-	if [ "${file_major}" -le "${FORMAT_MAJOR}" -o
-	   \( "${file_major}" -eq "${FORMAT_MAJOR}" -a
-	   "${file_minor}" -lt "${FORMAT_MINOR}" \) ]; then
-		errsolution="$ERR_DOWNLOAD"
-	else
-		errsolution="$ERR_UPGRADE"
-	fi
+if [ "${file_major}" -gt "${FORMAT_MAJOR}" -o "${file_minor}" -gt "${FORMAT_MINOR}" ]; then
+	echo "ERROR: Unsupported file format version"
+	echo "Please ensure you are running the latest version of audit-system"
+	exit 1
+fi
+
+if [ "${file_major}" -lt "${FORMAT_MAJOR}" -o "${file_minor}" -lt "${FORMAT_MINOR}" ]; then
+	echo "ERROR: Old version of system-vulnerabilities file detected"
+	exit 1
 fi
 
 # check integrity of vulnerabilities file
-check_integrity "$vuls" "$vuls"
+check_integrity "${vuls}"
 
 ${AWK} -v scriptdir="${scriptdir}" '
 /^#.*/	{ next }
