add 'show' action to view descriptions, options and pkgname.

diff --git a/apstget/files/apst-get b/apstget/files/apst-get
--- a/apstget/files/apst-get
+++ b/apstget/files/apst-get
@@ -3,9 +3,11 @@
 # APST-GET : Yet Another PkgSrc Tool to manage packages.
 #
 # AUTHOR: pancake < pancake@phreaker.net >
-# DATE: 2004/11/26
+# DATE: 2004/12/13
 #
 # depends: pkg_find, pkg_tarup, awk, pkglint
+#
+# TODO: add xfree/xorg paths into relink
 #
 
 if [ -e "_etc_/apstget.conf" ]; then
@@ -34,6 +36,7 @@ PKGFIND=${PREFIX}/bin/pkgfind
 PKGCHK=${PREFIX}/sbin/pkg_chk
 PKGSRC_DIR=_psd_
 DEFAULT_TARGETS="${DEFAULT_TARGETS}"
+CVS_RSH=ssh
 if [ "${CLEAN_BUILD}" = "" ]; then
 	CLEAN_BUILD="1"
 fi
@@ -102,6 +105,7 @@ do_usage() {
 	echo "  clean        - clean all build directories."
 	echo "  autoclean    - remove all outdated distfiles."
 	echo "  orphan       - list orphaned packages."
+	echo "  show         - show DESCR of target package."
 	echo ""
 	echo "variables (environ|_etc_/apstget.conf):"
 	echo "  CLEAN_BUILD=1, INTERACTIVE=1, QUITE=0, IGNORE_ERRORS=0"
@@ -523,6 +527,27 @@ case "$1" in
 			echo $A
 		fi
 	done
+	;;
+"show")
+	PKG=$2
+	DIR=$2
+	if [ "`echo $PKG | grep /`" = "" ]; then
+		DIR=`${PKGFIND} -qx $PKG`
+		if [ "${DIR}" = "" ]; then
+			echo "Package $1 not found."
+			exit 1
+		fi
+	fi
+	cd ${PKGSRC_DIR}/${DIR}
+	PKGNAM=`${MAKE} show-var VARNAME=PKGNAME`
+	PKGOPT=`${MAKE} show-var VARNAME=PKG_SUPPORTED_OPTIONS`
+	PKGDEP=`${MAKE} show-depends-dirs`
+	echo ">> PKGNAME: ${PKGNAM}"
+	if [ ! "${PKGOPT}" = "" ]; then
+	echo ">> OPTIONS: ${PKGOPT}"
+	fi
+	echo ">> DESCRIPTION:"
+	cat DESCR
 	;;
 *)
 	do_usage $0
