Update to 0.4.5.
ChangeLog:
        * Changed FBAS and SVHS to COMPOSITE and SVIDEO.
        * Moved nvtvsimple files to own directory, with own configure.
        * Adapted man directory for automake.
        * Changed x_includes to X_CFLAGS in configure.in, to fix
          Debian bug 192455.
        * Added nvtvsimple files from Mattias Eriksson.
        * Added automake files. Renamed LICENSE -> COPYING,
          main.[ch] -> nvtv.[ch], server.c -> nvtvd.c.
        * Updated xine info in FAQ.
        * Card argument for setup, proper mux setup for Voodoo3.
        * Added another Voodoo3 BT connector status detection.
        * Added PAL-M and NTSC-J converter for Brooktree/Conexant.
        * Added extra bus for I830.
        * Dump for i830 in probeCard.
        * Added CH7009 (Model2) detection and preleminary support.
        * Fixed devMem in nvdump.
        * Check if NV Timer is active before using it.
        * WxWin configure stuff (no WxWin files yet).
        * Fixed missing 'methods' in TvNull.
        * Support NVidia driver 1.0-4349.
        * Special init also for NV17, NV18, NV25, NV30.
        * Refactored identify mapping into card_direct.

On my side:
	o Instead of hacking configure script and some Makefiles, I hacked
	  configure.in and autoconf'ed it. I'll send the patch to the
	  author.
	o Use normal install target now that there are automake files. Now
	  binaries are in bin instead of sbin, and man page for nvtv goes
	  in section 1. Oh, well. I still want some docs to be installed.

diff --git a/nvtv/patches/patch-ab b/nvtv/patches/patch-ab
--- a/nvtv/patches/patch-ab
+++ b/nvtv/patches/patch-ab
@@ -1,94 +1,285 @@
-$NetBSD: patch-ab,v 1.1.1.1 2003/03/26 20:40:42 cubidou Exp $
+$NetBSD: patch-ab,v 1.2 2003/06/07 17:50:22 cubidou Exp $
 
---- configure.orig	2003-03-14 10:41:55.000000000 +0100
+--- configure.orig	2003-05-30 11:36:48.000000000 +0200
 +++ configure
-@@ -4400,7 +4400,7 @@ _ACEOF
+@@ -5101,7 +5101,7 @@ _ACEOF
  
-   SRCS_EXTRA="$SRCS_EXTRA actions.c"
+   OBJS_EXTRA="$OBJS_EXTRA actions.o"
    if test ${have_gtk} != no ; then
 -    have_gtk_version=`expr substr ${have_gtk} 4 1`
 +    have_gtk_version=`expr ${have_gtk} : '^gtk\([12]\)'`
  
  cat >>confdefs.h <<\_ACEOF
  #define HAVE_GTK 1
-@@ -4607,13 +4607,13 @@ fi
+@@ -5381,6 +5381,135 @@ echo "$as_me: error: math library requir
+ fi
  
  
- if test ${host_flag} = unix ; then
--  echo "$as_me:$LINENO: checking for pci_init in -lpci" >&5
--echo $ECHO_N "checking for pci_init in -lpci... $ECHO_C" >&6
-+  echo "$as_me:$LINENO: checking for pci_init in -lpciutils" >&5
-+echo $ECHO_N "checking for pci_init in -lpciutils... $ECHO_C" >&6
- if test "${ac_cv_lib_pci_pci_init+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   ac_check_lib_save_LIBS=$LIBS
--LIBS="-lpci  $LIBS"
-+LIBS="-lpciutils -lpci  $LIBS"
- cat >conftest.$ac_ext <<_ACEOF
- #line $LINENO "configure"
- /* confdefs.h.  */
-@@ -4662,7 +4662,7 @@ fi
++case ${host} in
++  *-*-netbsd*)
++    echo "$as_me:$LINENO: checking for i386_iopl in -li386" >&5
++echo $ECHO_N "checking for i386_iopl in -li386... $ECHO_C" >&6
++if test "${ac_cv_lib_i386_i386_iopl+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_check_lib_save_LIBS=$LIBS
++LIBS="-li386  $LIBS"
++cat >conftest.$ac_ext <<_ACEOF
++#line $LINENO "configure"
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char i386_iopl ();
++int
++main ()
++{
++i386_iopl ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++         { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_cv_lib_i386_i386_iopl=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_cv_lib_i386_i386_iopl=no
++fi
++rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
++LIBS=$ac_check_lib_save_LIBS
++fi
++echo "$as_me:$LINENO: result: $ac_cv_lib_i386_i386_iopl" >&5
++echo "${ECHO_T}$ac_cv_lib_i386_i386_iopl" >&6
++if test $ac_cv_lib_i386_i386_iopl = yes; then
++  LIBS="$LIBS -li386"
++else
++  { { echo "$as_me:$LINENO: error: NetBSD i386 library required" >&5
++echo "$as_me: error: NetBSD i386 library required" >&2;}
++   { (exit 1); exit 1; }; }
++fi
++
++    echo "$as_me:$LINENO: checking for pcibus_conf_read in -lpci" >&5
++echo $ECHO_N "checking for pcibus_conf_read in -lpci... $ECHO_C" >&6
++if test "${ac_cv_lib_pci_pcibus_conf_read+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_check_lib_save_LIBS=$LIBS
++LIBS="-lpci  $LIBS"
++cat >conftest.$ac_ext <<_ACEOF
++#line $LINENO "configure"
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char pcibus_conf_read ();
++int
++main ()
++{
++pcibus_conf_read ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++         { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_cv_lib_pci_pcibus_conf_read=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_cv_lib_pci_pcibus_conf_read=no
++fi
++rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
++LIBS=$ac_check_lib_save_LIBS
++fi
++echo "$as_me:$LINENO: result: $ac_cv_lib_pci_pcibus_conf_read" >&5
++echo "${ECHO_T}$ac_cv_lib_pci_pcibus_conf_read" >&6
++if test $ac_cv_lib_pci_pcibus_conf_read = yes; then
++  LIBS="$LIBS -lpci"
++else
++  { { echo "$as_me:$LINENO: error: NetBSD pci library required" >&5
++echo "$as_me: error: NetBSD pci library required" >&2;}
++   { (exit 1); exit 1; }; }
++fi
++
++  ;;
++esac
++
+ if test ${with_winio} = yes ; then
+   echo "$as_me:$LINENO: checking for winio_init in -lwinio" >&5
+ echo $ECHO_N "checking for winio_init in -lwinio... $ECHO_C" >&6
+@@ -5502,7 +5631,64 @@ fi
  echo "$as_me:$LINENO: result: $ac_cv_lib_pci_pci_init" >&5
  echo "${ECHO_T}$ac_cv_lib_pci_pci_init" >&6
  if test $ac_cv_lib_pci_pci_init = yes; then
 -  LIBS="$LIBS -lpci"
-+  LIBS="$LIBS -lpciutils -lpci"
++  LIBS="$LIBS -lpci" pciutils_libname="pci"
++else
++  echo "$as_me:$LINENO: checking for pci_init in -lpciutils" >&5
++echo $ECHO_N "checking for pci_init in -lpciutils... $ECHO_C" >&6
++if test "${ac_cv_lib_pciutils_pci_init+set}" = set; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  ac_check_lib_save_LIBS=$LIBS
++LIBS="-lpciutils  $LIBS"
++cat >conftest.$ac_ext <<_ACEOF
++#line $LINENO "configure"
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++
++/* Override any gcc2 internal prototype to avoid an error.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++/* We use char because int might match the return type of a gcc2
++   builtin and then its argument prototype would still apply.  */
++char pci_init ();
++int
++main ()
++{
++pci_init ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
++  (eval $ac_link) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++         { ac_try='test -s conftest$ac_exeext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
++  ac_cv_lib_pciutils_pci_init=yes
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++ac_cv_lib_pciutils_pci_init=no
++fi
++rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
++LIBS=$ac_check_lib_save_LIBS
++fi
++echo "$as_me:$LINENO: result: $ac_cv_lib_pciutils_pci_init" >&5
++echo "${ECHO_T}$ac_cv_lib_pciutils_pci_init" >&6
++if test $ac_cv_lib_pciutils_pci_init = yes; then
++  LIBS="$LIBS -lpciutils" pciutils_libname="pciutils"
  else
    { { echo "$as_me:$LINENO: error: pci library required" >&5
  echo "$as_me: error: pci library required" >&2;}
-@@ -5044,8 +5044,8 @@ done
+@@ -5511,6 +5697,8 @@ fi
+ 
+ fi
+ 
++fi
++
+ 
+ if test ${with_x} = yes ; then
+   echo "$as_me:$LINENO: checking for XF86VidModeQueryVersion in -lXxf86vm" >&5
+@@ -6029,18 +6217,19 @@ done
  
  
- if test "${ac_cv_header_pci_pci_h+set}" = set; then
+ if test ${host_flag} = unix -o ${with_winio} = yes ; then
+-  if test "${ac_cv_header_pci_pci_h+set}" = set; then
 -  echo "$as_me:$LINENO: checking for pci/pci.h" >&5
 -echo $ECHO_N "checking for pci/pci.h... $ECHO_C" >&6
-+  echo "$as_me:$LINENO: checking for pciutils/pci.h" >&5
-+echo $ECHO_N "checking for pciutils/pci.h... $ECHO_C" >&6
- if test "${ac_cv_header_pci_pci_h+set}" = set; then
+-if test "${ac_cv_header_pci_pci_h+set}" = set; then
++  as_ac_Header=`echo "ac_cv_header_${pciutils_libname}/pci.h" | $as_tr_sh`
++if eval "test \"\${$as_ac_Header+set}\" = set"; then
++  echo "$as_me:$LINENO: checking for ${pciutils_libname}/pci.h" >&5
++echo $ECHO_N "checking for ${pciutils_libname}/pci.h... $ECHO_C" >&6
++if eval "test \"\${$as_ac_Header+set}\" = set"; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  fi
-@@ -5053,8 +5053,8 @@ echo "$as_me:$LINENO: result: $ac_cv_hea
- echo "${ECHO_T}$ac_cv_header_pci_pci_h" >&6
+-echo "$as_me:$LINENO: result: $ac_cv_header_pci_pci_h" >&5
+-echo "${ECHO_T}$ac_cv_header_pci_pci_h" >&6
++echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
++echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
  else
    # Is the header compilable?
 -echo "$as_me:$LINENO: checking pci/pci.h usability" >&5
 -echo $ECHO_N "checking pci/pci.h usability... $ECHO_C" >&6
-+echo "$as_me:$LINENO: checking pciutils/pci.h usability" >&5
-+echo $ECHO_N "checking pciutils/pci.h usability... $ECHO_C" >&6
++echo "$as_me:$LINENO: checking ${pciutils_libname}/pci.h usability" >&5
++echo $ECHO_N "checking ${pciutils_libname}/pci.h usability... $ECHO_C" >&6
  cat >conftest.$ac_ext <<_ACEOF
  #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -5063,7 +5063,7 @@ cat confdefs.h >>conftest.$ac_ext
+@@ -6049,7 +6238,7 @@ cat confdefs.h >>conftest.$ac_ext
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
  $ac_includes_default
 -#include <pci/pci.h>
-+#include <pciutils/pci.h>
++#include <${pciutils_libname}/pci.h>
  _ACEOF
  rm -f conftest.$ac_objext
  if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-@@ -5089,8 +5089,8 @@ echo "$as_me:$LINENO: result: $ac_header
+@@ -6075,8 +6264,8 @@ echo "$as_me:$LINENO: result: $ac_header
  echo "${ECHO_T}$ac_header_compiler" >&6
  
  # Is the header present?
 -echo "$as_me:$LINENO: checking pci/pci.h presence" >&5
 -echo $ECHO_N "checking pci/pci.h presence... $ECHO_C" >&6
-+echo "$as_me:$LINENO: checking pciutils/pci.h presence" >&5
-+echo $ECHO_N "checking pciutils/pci.h presence... $ECHO_C" >&6
++echo "$as_me:$LINENO: checking ${pciutils_libname}/pci.h presence" >&5
++echo $ECHO_N "checking ${pciutils_libname}/pci.h presence... $ECHO_C" >&6
  cat >conftest.$ac_ext <<_ACEOF
  #line $LINENO "configure"
  /* confdefs.h.  */
-@@ -5098,7 +5098,7 @@ _ACEOF
+@@ -6084,7 +6273,7 @@ _ACEOF
  cat confdefs.h >>conftest.$ac_ext
  cat >>conftest.$ac_ext <<_ACEOF
  /* end confdefs.h.  */
 -#include <pci/pci.h>
-+#include <pciutils/pci.h>
++#include <${pciutils_libname}/pci.h>
  _ACEOF
  if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
    (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-@@ -5131,10 +5131,10 @@ echo "${ECHO_T}$ac_header_preproc" >&6
+@@ -6117,10 +6306,10 @@ echo "${ECHO_T}$ac_header_preproc" >&6
  # So?  What about this header?
  case $ac_header_compiler:$ac_header_preproc in
    yes:no )
@@ -96,14 +287,14 @@ $NetBSD: patch-ab,v 1.1.1.1 2003/03/26 20:40:42 cubidou Exp $
 -echo "$as_me: WARNING: pci/pci.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: pci/pci.h: proceeding with the preprocessor's result" >&5
 -echo "$as_me: WARNING: pci/pci.h: proceeding with the preprocessor's result" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: pciutils/pci.h: accepted by the compiler, rejected by the preprocessor!" >&5
-+echo "$as_me: WARNING: pciutils/pci.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: pciutils/pci.h: proceeding with the preprocessor's result" >&5
-+echo "$as_me: WARNING: pciutils/pci.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: ${pciutils_libname}/pci.h: accepted by the compiler, rejected by the preprocessor!" >&5
++echo "$as_me: WARNING: ${pciutils_libname}/pci.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
++    { echo "$as_me:$LINENO: WARNING: ${pciutils_libname}/pci.h: proceeding with the preprocessor's result" >&5
++echo "$as_me: WARNING: ${pciutils_libname}/pci.h: proceeding with the preprocessor's result" >&2;}
      (
        cat <<\_ASBOX
  ## ------------------------------------ ##
-@@ -5145,12 +5145,12 @@ _ASBOX
+@@ -6131,12 +6320,12 @@ _ASBOX
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
    no:yes )
@@ -113,34 +304,59 @@ $NetBSD: patch-ab,v 1.1.1.1 2003/03/26 20:40:42 cubidou Exp $
 -echo "$as_me: WARNING: pci/pci.h: check for missing prerequisite headers?" >&2;}
 -    { echo "$as_me:$LINENO: WARNING: pci/pci.h: proceeding with the preprocessor's result" >&5
 -echo "$as_me: WARNING: pci/pci.h: proceeding with the preprocessor's result" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: pciutils/pci.h: present but cannot be compiled" >&5
-+echo "$as_me: WARNING: pciutils/pci.h: present but cannot be compiled" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: pciutils/pci.h: check for missing prerequisite headers?" >&5
-+echo "$as_me: WARNING: pciutils/pci.h: check for missing prerequisite headers?" >&2;}
-+    { echo "$as_me:$LINENO: WARNING: pciutils/pci.h: proceeding with the preprocessor's result" >&5
-+echo "$as_me: WARNING: pciutils/pci.h: proceeding with the preprocessor's result" >&2;}
++    { echo "$as_me:$LINENO: WARNING: ${pciutils_libname}/pci.h: present but cannot be compiled" >&5
++echo "$as_me: WARNING: ${pciutils_libname}/pci.h: present but cannot be compiled" >&2;}
++    { echo "$as_me:$LINENO: WARNING: ${pciutils_libname}/pci.h: check for missing prerequisite headers?" >&5
++echo "$as_me: WARNING: ${pciutils_libname}/pci.h: check for missing prerequisite headers?" >&2;}
++    { echo "$as_me:$LINENO: WARNING: ${pciutils_libname}/pci.h: proceeding with the preprocessor's result" >&5
++echo "$as_me: WARNING: ${pciutils_libname}/pci.h: proceeding with the preprocessor's result" >&2;}
      (
        cat <<\_ASBOX
  ## ------------------------------------ ##
-@@ -5161,8 +5161,8 @@ _ASBOX
+@@ -6147,23 +6336,22 @@ _ASBOX
        sed "s/^/$as_me: WARNING:     /" >&2
      ;;
  esac
 -echo "$as_me:$LINENO: checking for pci/pci.h" >&5
 -echo $ECHO_N "checking for pci/pci.h... $ECHO_C" >&6
-+echo "$as_me:$LINENO: checking for pciutils/pci.h" >&5
-+echo $ECHO_N "checking for pciutils/pci.h... $ECHO_C" >&6
- if test "${ac_cv_header_pci_pci_h+set}" = set; then
+-if test "${ac_cv_header_pci_pci_h+set}" = set; then
++echo "$as_me:$LINENO: checking for ${pciutils_libname}/pci.h" >&5
++echo $ECHO_N "checking for ${pciutils_libname}/pci.h... $ECHO_C" >&6
++if eval "test \"\${$as_ac_Header+set}\" = set"; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
-@@ -5175,8 +5175,8 @@ fi
- if test $ac_cv_header_pci_pci_h = yes; then
+-  ac_cv_header_pci_pci_h=$ac_header_preproc
++  eval "$as_ac_Header=$ac_header_preproc"
+ fi
+-echo "$as_me:$LINENO: result: $ac_cv_header_pci_pci_h" >&5
+-echo "${ECHO_T}$ac_cv_header_pci_pci_h" >&6
++echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
++echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+ 
+ fi
+-if test $ac_cv_header_pci_pci_h = yes; then
++if test `eval echo '${'$as_ac_Header'}'` = yes; then
    :
  else
 -  { { echo "$as_me:$LINENO: error: pci library header 'pci/pci.h' required" >&5
 -echo "$as_me: error: pci library header 'pci/pci.h' required" >&2;}
-+  { { echo "$as_me:$LINENO: error: pci library header 'pciutils/pci.h' required" >&5
-+echo "$as_me: error: pci library header 'pciutils/pci.h' required" >&2;}
-    { (exit 1); exit 1; }; }
+-   { (exit 1); exit 1; }; }
++  { echo "$as_me:$LINENO: WARNING: pci library header \'${pciutils_libname}/pci.h\' required" >&5
++echo "$as_me: WARNING: pci library header \'${pciutils_libname}/pci.h\' required" >&2;}
  fi
  
+ 
+@@ -6172,6 +6360,13 @@ cat >>confdefs.h <<\_ACEOF
+ #define HAVE_PCI 1
+ _ACEOF
+ 
++  if test ${pciutils_libname} = pciutils ; then
++
++cat >>confdefs.h <<\_ACEOF
++#define HAVE_PCIUTILS 1
++_ACEOF
++
++  fi
+ fi
+ 
+ if test ${with_winio} = yes ; then
