Fix detection of ccrtp (pkg-config file name changed for 2.x).
Build now dies in
log.cpp: In member function 'void t_log::write_header(const std::string&, t_log_class, t_log_severity)':
log.cpp:164:24: error: call of overloaded 'localtime_r(time_t*, tm*)' is ambiguous

diff --git a/twinkle/patches/patch-aa b/twinkle/patches/patch-aa
--- a/twinkle/patches/patch-aa
+++ b/twinkle/patches/patch-aa
@@ -1,9 +1,59 @@
-$NetBSD: patch-aa,v 1.3 2011/11/10 13:19:39 othyro Exp $
+$NetBSD: patch-aa,v 1.4 2012/02/25 19:18:05 thomasklausner Exp $
 
 Fixes improperly nested conditional and removes double = test.
+libccrtp was updated to 2, fix detection.
 
---- configure.orig	2009-01-31 04:48:59.000000000 +0000
+--- configure.orig	2009-02-25 20:15:58.000000000 +0000
 +++ configure
+@@ -6772,23 +6772,23 @@ fi
+   else
+      PKG_CONFIG_MIN_VERSION=0.9.0
+      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+-        { echo "$as_me:$LINENO: checking for libccrtp1 >= 1.6.0" >&5
+-echo $ECHO_N "checking for libccrtp1 >= 1.6.0... $ECHO_C" >&6; }
++        { echo "$as_me:$LINENO: checking for libccrtp >= 1.6.0" >&5
++echo $ECHO_N "checking for libccrtp >= 1.6.0... $ECHO_C" >&6; }
+ 
+-        if $PKG_CONFIG --exists "libccrtp1 >= 1.6.0" ; then
++        if $PKG_CONFIG --exists "libccrtp >= 1.6.0" ; then
+             { echo "$as_me:$LINENO: result: yes" >&5
+ echo "${ECHO_T}yes" >&6; }
+             succeeded=yes
+ 
+             { echo "$as_me:$LINENO: checking CCRTP_CFLAGS" >&5
+ echo $ECHO_N "checking CCRTP_CFLAGS... $ECHO_C" >&6; }
+-            CCRTP_CFLAGS=`$PKG_CONFIG --cflags "libccrtp1 >= 1.6.0"`
++            CCRTP_CFLAGS=`$PKG_CONFIG --cflags "libccrtp >= 1.6.0"`
+             { echo "$as_me:$LINENO: result: $CCRTP_CFLAGS" >&5
+ echo "${ECHO_T}$CCRTP_CFLAGS" >&6; }
+ 
+             { echo "$as_me:$LINENO: checking CCRTP_LIBS" >&5
+ echo $ECHO_N "checking CCRTP_LIBS... $ECHO_C" >&6; }
+-            CCRTP_LIBS=`$PKG_CONFIG --libs "libccrtp1 >= 1.6.0"`
++            CCRTP_LIBS=`$PKG_CONFIG --libs "libccrtp >= 1.6.0"`
+             { echo "$as_me:$LINENO: result: $CCRTP_LIBS" >&5
+ echo "${ECHO_T}$CCRTP_LIBS" >&6; }
+         else
+@@ -6796,7 +6796,7 @@ echo "${ECHO_T}$CCRTP_LIBS" >&6; }
+             CCRTP_LIBS=""
+             ## If we have a custom action on failure, don't print errors, but
+             ## do set a variable so people can do so.
+-            CCRTP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libccrtp1 >= 1.6.0"`
++            CCRTP_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libccrtp >= 1.6.0"`
+             echo $CCRTP_PKG_ERRORS
+         fi
+ 
+@@ -6811,8 +6811,8 @@ echo "${ECHO_T}$CCRTP_LIBS" >&6; }
+   if test $succeeded = yes; then
+      :
+   else
+-     { { echo "$as_me:$LINENO: error: Library requirements (libccrtp1 >= 1.6.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+-echo "$as_me: error: Library requirements (libccrtp1 >= 1.6.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
++     { { echo "$as_me:$LINENO: error: Library requirements (libccrtp >= 1.6.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
++echo "$as_me: error: Library requirements (libccrtp >= 1.6.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+    { (exit 1); exit 1; }; }
+   fi
+ 
 @@ -13394,7 +13394,7 @@ cat >>confdefs.h <<_ACEOF
  _ACEOF
  
@@ -21,6 +71,18 @@ Fixes improperly nested conditional and removes double = test.
  
  rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
  
+@@ -16729,9 +16730,9 @@ done
+ ) | grep '^-I' | sed -e 's|^-I||' | xargs echo INCLUDEPATH += >> $QT_INCL_PRO
+ 
+ #echo "INCLUDEPATH += `$CCGNU2_CONFIG --includes`" | sed -e s/-I//g > $QT_INCL_PRO
+-# libccrtp1(ccrtp) depend from libccgnu2(commoncpp2) and
++# libccrtp(ccrtp) depend from libccgnu2(commoncpp2) and
+ # should include above flags !
+-echo "INCLUDEPATH += `$PKG_CONFIG --cflags-only-I libccrtp1`" | sed -e s/-I//g >> $QT_INCL_PRO
++echo "INCLUDEPATH += `$PKG_CONFIG --cflags-only-I libccrtp`" | sed -e s/-I//g >> $QT_INCL_PRO
+ echo "INCLUDEPATH += `$PKG_CONFIG --cflags-only-I libxml-2.0`" | sed -e s/-I//g >> $QT_INCL_PRO
+ 
+ # get libraries specified on command line
 @@ -21448,7 +21449,7 @@ done
      fi
    fi
