Update to 0.6.4a; PKG_OPTIONS-ize the type of crypto used and the databases available for the datastore.  It almost works now.
(On NetBSD 2.0, it runs for me, but has a lot of trouble trying to connect
to peers; it will open connections in nonblocking mode, but somehow not get
any responses to "sent" data. Methinks there are some nonblocking socket
no-no's in the code that just happen to work on Linux.)

diff --git a/gnunet/patches/patch-aa b/gnunet/patches/patch-aa
--- a/gnunet/patches/patch-aa
+++ b/gnunet/patches/patch-aa
@@ -1,72 +1,53 @@
-$NetBSD: patch-aa,v 1.3 2003/07/18 05:59:22 xtraeme Exp $
+$NetBSD: patch-aa,v 1.4 2004/11/06 03:35:19 tvierling Exp $
 
---- src/util/semaphore.c.orig	2003-07-18 06:52:23.000000000 +0200
-+++ src/util/semaphore.c	2003-07-18 06:56:26.000000000 +0200
-@@ -33,10 +33,16 @@
- #include "util/xmalloc.h"
- #include "util/returnvalues.h"
+--- configure.orig	2004-09-25 23:24:06.000000000 -0400
++++ configure
+@@ -24831,9 +24831,9 @@ fi
  
-+#ifdef __NetBSD__
-+# include <sys/param.h> /* __NetBSD_Version__ */
-+#endif
-+
- #include <errno.h>
- #include <string.h>
--#ifdef SOMEBSD
-+#ifdef __FreeBSD__
- # include <pthread_np.h>
-+#elif HAVE_LIBPTHREAD
-+# include <pthread.h>
- #endif
+ fi;
  
- #define DEBUG_SEMUPDOWN NO
-@@ -74,10 +80,14 @@
-   pthread_mutexattr_setkind_np(&attr,
- 			       PTHREAD_MUTEX_ERRORCHECK_NP);  
- #endif
--#else
-+#elif __FreeBSD__
-   pthread_mutexattr_setkind_np(&attr,
- 			       (int)PTHREAD_MUTEX_NORMAL);
--#endif
-+#else
-+  pthread_mutexattr_settype(&attr,
-+		  		(int)PTHREAD_MUTEX_NORMAL);
-+#endif /* POSIX threads */
-+  
-   if ( pthread_mutex_init(&mutex->pthreadMutex, &attr) != 0)
-     errexit("FATAL: creation of mutex failed (%s)",
- 	    strerror(errno));
-@@ -90,16 +100,14 @@
- #ifdef LINUX
-   pthread_mutexattr_setkind_np(&attr,  
- 			       PTHREAD_MUTEX_RECURSIVE_NP);
--#elif SOMEBSD
-+#elif __FreeBSD__
-   pthread_mutexattr_setkind_np(&attr,
- 			       PTHREAD_MUTEX_RECURSIVE);
--#elif SOLARIS
--  pthread_mutexattr_settype(&attr,
--			    PTHREAD_MUTEX_RECURSIVE);
--#elif CYGWIN
-+#else 
-   pthread_mutexattr_settype(&attr,
- 			    PTHREAD_MUTEX_RECURSIVE);
--#endif
-+#endif /* POSIX threads */
-+
-   if ( pthread_mutex_init(&mutex->pthreadMutex, &attr) != 0)
-     errexit("FATAL: creation of recursive mutex failed");
- }
-@@ -288,8 +296,11 @@
-   pthread_attr_t stack_size_custom_attr;
+-if test $openssl == 0
++if test $openssl = 0
+ then
+-if test $gcrypt == 0
++if test $gcrypt = 0
+ then
+   { { echo "$as_me:$LINENO: error: GNUnet needs libgcrypt or OpenSSL" >&5
+ echo "$as_me: error: GNUnet needs libgcrypt or OpenSSL" >&2;}
+@@ -24842,9 +24842,9 @@ fi
+ fi
  
-   pthread_attr_init(&stack_size_custom_attr);
-+#if __NetBSD_Version__ <= 106130000  
-   pthread_attr_setstacksize(&stack_size_custom_attr,
- 			    stackSize);
-+#endif /* NetBSD -current these days hasn't those functions yet */
-+
-   return pthread_create(handle, 
- 			&stack_size_custom_attr,
- 			main, 
+ # Given the choice, the preference is libgcrypt
+-if test $openssl == 1
++if test $openssl = 1
+ then
+-if test $gcrypt == 1
++if test $gcrypt = 1
+ then
+ openssl=0
+ fi
+@@ -34315,7 +34315,7 @@ then
+ fi
+ 
+ guile=0
+-if test "$enable_guile" == "yes"
++if test "$enable_guile" = "yes"
+ then
+     # Extract the first word of "guile", so it can be a program name with args.
+ set dummy guile; ac_word=$2
+@@ -36633,13 +36633,13 @@ fi
+ { echo "$as_me:$LINENO: NOTICE: Database support is set to GDBM: $gdb, TDB: $tdb, BDB: $bdb, MySQL: $mysql" >&5
+ echo "$as_me: NOTICE: Database support is set to GDBM: $gdb, TDB: $tdb, BDB: $bdb, MySQL: $mysql" >&6;}
+ 
+-if test $openssl == 1
++if test $openssl = 1
+ then
+   { echo "$as_me:$LINENO: NOTICE: Using OpenSSL for cryptographic primitives." >&5
+ echo "$as_me: NOTICE: Using OpenSSL for cryptographic primitives." >&6;}
+ fi
+ 
+-if test $gcrypt == 1
++if test $gcrypt = 1
+ then
+   { echo "$as_me:$LINENO: NOTICE: Using libgcrypt for cryptographic primitives." >&5
+ echo "$as_me: NOTICE: Using libgcrypt for cryptographic primitives." >&6;}
