Stop configure looking for ORBit and disable mysqlfs

diff --git a/mysql4-server/patches/patch-af b/mysql4-server/patches/patch-af
--- a/mysql4-server/patches/patch-af
+++ b/mysql4-server/patches/patch-af
@@ -1,7 +1,7 @@
-$NetBSD: patch-af,v 1.2 2003/07/09 21:51:04 adrian_p Exp $
+$NetBSD: patch-af,v 1.3 2003/07/10 22:49:26 adrian_p Exp $
 
 --- configure.orig	Wed May 14 21:24:53 2003
-+++ configure	Wed Jul  9 21:15:24 2003
++++ configure	Thu Jul 10 23:31:59 2003
 @@ -19778,7 +19778,7 @@
   tell atod memcpy memmove \
   setupterm strcasecmp sighold vidattr lrand48 localtime_r \
@@ -11,7 +11,35 @@ $NetBSD: patch-af,v 1.2 2003/07/09 21:51:04 adrian_p Exp $
   pthread_attr_create pthread_getsequence_np pthread_attr_setstacksize \
   pthread_attr_getstacksize \
   pthread_condattr_create rwlock_init pthread_rwlock_rdlock \
-@@ -20999,7 +20999,6 @@
+@@ -20795,27 +20795,11 @@
+ 
+ echo "$as_me:$LINENO: checking for ORBit" >&5
+ echo $ECHO_N "checking for ORBit... $ECHO_C" >&6
+-orbit_config_path=`which orbit-config`
+-if test -n "$orbit_config_path" -a $? = 0
+-then
+-  orbit_exec_prefix=`orbit-config --exec-prefix`
+-  orbit_includes=`orbit-config --cflags server`
+-  orbit_libs=`orbit-config --libs server`
+-  orbit_idl="$orbit_exec_prefix/bin/orbit-idl"
+-  echo "$as_me:$LINENO: result: found!" >&5
+-echo "${ECHO_T}found!" >&6
+-  cat >>confdefs.h <<\_ACEOF
+-#define HAVE_ORBIT 1
+-_ACEOF
+-
+-else
+   orbit_exec_prefix=
+   orbit_includes=
+   orbit_libs=
+   orbit_idl=
+   echo "$as_me:$LINENO: result: not found" >&5
+-echo "${ECHO_T}not found" >&6
+-fi
+ 
+ 
+ 
+@@ -20999,7 +20983,6 @@
  else
    bench_dirs=""
  fi
